const { client: redisClient } = require('../config/redis');
const { client: esClient } = require('../config/elasticsearch');
const { client: chClient } = require('../config/clickhouse');

const CORRELATION_ALERTS_TOPIC = 'new_alert'; // Publishes to WebSocket

const correlationEngine = {
  processAlert: async (alert) => {
    const { sourceIp, destIp, threatType, severity, mitreId, mitreName, tags, description } = alert;

    if (!sourceIp || sourceIp === '0.0.0.0' || sourceIp === '127.0.0.1') return;

    try {
      // Rule 1: Host Alert Flooding (DDoS/Brute Force indicators)
      const floodKey = `siem:flood:${sourceIp}`;
      const count = await redisClient.incr(floodKey);
      
      if (count === 1) {
        // Set TTL of 10 seconds for the window
        await redisClient.expire(floodKey, 10);
      }

      if (count === 10) { // Trigger only once when threshold is reached
        const desc = `SIEM Correlation: Host ${sourceIp} triggered ${count} alerts within a 10s window. Possible DDoS or automated credential stuffing.`;
        await triggerCorrelatedAlert({
          sourceIp,
          destIp,
          threatType: 'Alert Flooding',
          severity: 'high',
          description: desc,
          mitreId: 'T1110', // Brute Force
          mitreName: 'Credential Access',
          tags: ['correlated', 'flood', 'ddos', 'brute-force']
        });
      }

      // Rule 2: Multi-Stage Attack Path (Mitre Tactic chaining)
      // We look at mitreId or tags to trace reconnaissance followed by compromise
      const isRecon = mitreId === 'TA0043' || (tags && (tags.includes('scanning') || tags.includes('recon')));
      const isCompromise = ['TA0001', 'TA0011', 'T1071', 'T1587.001'].includes(mitreId) || (tags && (tags.includes('ai') || tags.includes('c2') || tags.includes('beaconing') || tags.includes('malware')));

      const stageKey = `siem:stages:${sourceIp}`;
      
      if (isRecon) {
        await redisClient.sAdd(stageKey, 'recon');
        await redisClient.expire(stageKey, 60); // 1-minute tracking window
      }

      if (isCompromise) {
        const hasRecon = await redisClient.sIsMember(stageKey, 'recon');
        if (hasRecon) {
          const desc = `SIEM Correlation: Multi-stage attack detected from host ${sourceIp}. Observed Reconnaissance activity followed by host compromise / C2 channel establishment within 60s.`;
          await triggerCorrelatedAlert({
            sourceIp,
            destIp,
            threatType: 'Multi-Stage Attack',
            severity: 'critical',
            description: desc,
            mitreId: 'TA0008', // Lateral Movement or C2 chain
            mitreName: 'Lateral Movement',
            tags: ['correlated', 'multi-stage', 'c2', 'intrusion']
          });
          
          // Clear correlation state
          await redisClient.del(stageKey);
        }
      }
    } catch (error) {
      console.error('[Correlation Engine] Processing failed', error.stack || error.message);
    }
  }
};

const triggerCorrelatedAlert = async (correlatedAlert) => {
  const timestamp = new Date().toISOString();
  const alertData = {
    ...correlatedAlert,
    timestamp,
    status: 'active',
    acknowledgedBy: null,
    notes: 'Generated by CyberWall Autonomous SIEM Correlation Engine'
  };

  console.log(`[Correlation Engine] TRIGGERED CORRELATED ALERT: [${alertData.severity.toUpperCase()}] ${alertData.description}`);

  try {
    // 1. Index in Elasticsearch
    await esClient.index({
      index: 'cyberwall-events',
      body: {
        ...alertData,
        eventType: 'alert'
      }
    });

    // 2. Insert into ClickHouse
    const chAlert = {
      timestamp: Date.now(),
      sourceIp: alertData.sourceIp,
      destIp: alertData.destIp || '0.0.0.0',
      threatType: alertData.threatType,
      severity: alertData.severity,
      description: alertData.description,
      mitreId: alertData.mitreId,
      mitreName: alertData.mitreName,
      tags: alertData.tags
    };

    await chClient.insert({
      table: 'default.alert_logs',
      values: [chAlert],
      format: 'JSONEachRow'
    });

    // 3. Publish to Redis Pub/Sub for immediate SOC updates
    await redisClient.publish(CORRELATION_ALERTS_TOPIC, JSON.stringify(alertData));
  } catch (error) {
    console.error('[Correlation Engine] Failed to store/publish correlated alert', error.message);
  }
};

module.exports = { correlationEngine };
